### ISSUE TITLE
pymysql.err.OperationalError: (1812, 'Tablespace is missing for table `demo`.`project`.')

### ISSUE THREAD

**Issue by liuheo** [anyongjin/mysql_ibd#11]
pymysql.err.OperationalError: (1812, 'Tablespace is missing for table `demo`.`project`.')

**Comment by anyongjin** [comment]
This error seems to be related to the ibd file, indicating that the ibd file cannot be read or accessed properly. For detailed information, you can refer to: https://bobcares.com/blog/mysql-tablespace-is-missing-for-table/

**Comment by itliujia** [comment]
你好，我最近正在学习中，无法亲自回复你的邮件。我将尽快给你回复。

**Comment by liuheo** [comment]
Thank you very much, I have found the problem, is when the import data, the database data directory does not have.ibd file, manual copy can be used normally.
