### ISSUE TITLE
处理中文comment

### ISSUE THREAD

**Issue by TSOTOF** [anyongjin/mysql_ibd#13]
ibd文件中出现中文comment时可以正常生成sql文件，但sql文件运行时会报错。
这是因为生成的sql文件中COMMENT后面直接接上了comment的内容，当出现中文时无法识别，因此需要在原代码main.py的第98行中，将``builder.write(f" COMMENT {comment}")`` 改成 ``builder.write(f" COMMENT '{comment}'")``，也就是在{ }两边加上两个单引号，这样就解决这个问题啦！

**Comment by anyongjin** [comment]
已兼容，感谢反馈~
