### ISSUE TITLE
line 239 error

### ISSUE THREAD

**Issue by demirciberkan** [anyongjin/mysql_ibd#20]
i get the error below for load_data
Traceback (most recent call last):
  File "/home/mysql_ibd/main.py", line 239, in <module>
    command_mapping[args.cmd]()
TypeError: link_tables_ibd() missing 1 required positional argument: 'config'

and the error below for tosql
Traceback (most recent call last):
  File "/home/mysql_ibd/main.py", line 239, in <module>
    command_mapping[args.cmd]()
TypeError: ibd2sql() missing 1 required positional argument: 'args'

what would be wrong

**Comment by anyongjin** [comment]
Thanks for the feedback, it has been resolved. Please pull the latest code and try again

**Comment by demirciberkan** [comment]
Solved.
