### ISSUE TITLE
quotes when creating sql using tosql

### ISSUE THREAD

**Issue by demirciberkan** [anyongjin/mysql_ibd#21]
Here is an example produced by the tosql arg.

DROP TABLE IF EXISTS `account_sessions`;
CREATE TABLE `account_sessions` (
	`session_id` varchar(255) NOT NULL,
	`account_id` int unsigned NOT NULL,
	`login_time` timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
	PRIMARY KEY (`session_id`)
) ENGINE=InnoDB;

CURRENT_TIMESTAMP should not be quoted as string here

**Comment by anyongjin** [comment]
Thanks for the feedback, it should has been resolved. Please pull the latest code and try again. 
If you encounter any issues and know how to solve them, you are also welcome to submit a pull request directly

**Comment by demirciberkan** [comment]
Thank you so much
