### ISSUE TITLE
ibd2sdi not found

### ISSUE THREAD

**Issue by Bovive** [anyongjin/mysql_ibd#7]
Running this on Ubuntu. When I run "sudo python3 main.py tosql" I received this error:

raise ValueError('no installed `ibd2sdi` found on system!')
ValueError: no installed `ibd2sdi` found on system!

Is there a way to fix this? Thank you very much!

**Comment by anyongjin** [comment]
ibd2sdi is a tool that comes with mysql 8. 
So you should run this script on a machine which with mysql 8 installed, or you can install mysql 8 first.
thank you
