### ISSUE TITLE
pymysql module missing

### ISSUE THREAD

**Issue by carloslimajr** [anyongjin/mysql_ibd#8]
root@local:/home/me/mysql_ibd# python3 main.py load_data
Traceback (most recent call last):
  File "main.py", line 194, in <module>
    link_tables_ibd(config)
  File "main.py", line 129, in link_tables_ibd
    import pymysql
ModuleNotFoundError: No module named 'pymysql'

**Comment by anyongjin** [comment]
this is a python script which requires pymysql module and `mysql` installed. So please install pymysql first with `pip install PyMySQL`
